repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
        stages: [pre-commit]
        args: [
          --markdown-linebreak-ext=md
        ]
      - id: end-of-file-fixer
        stages: [pre-commit]
      - id: check-json
        stages: [pre-commit]
      - id: check-yaml
        stages: [pre-commit]
        args:
          - --unsafe
      - id: detect-private-key
        stages: [pre-commit]
  # requires the dependencies installing
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.96.2
    hooks:
      - id: terraform_fmt
        stages: [pre-commit]
      - id: terraform_tflint
        stages: [pre-commit]
        exclude: ^examples
      - id: terraform_docs
        stages: [pre-commit]
      - id: terraform_validate
        stages: [pre-commit]
  - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
    rev: v9.18.0
    hooks:
      - id: commitlint
        stages: [commit-msg]
        additional_dependencies: ["@commitlint/config-conventional"]
        pass_filenames: false
  - repo: https://github.com/bridgecrewio/checkov.git
    rev: '3.2.305'
    hooks:
      - id: checkov
        stages: [pre-commit]
